swagger: '2.0'
info:
  title: Remove Retweet API
  description: API for removing a retweet
  version: '1.0'
basePath: /api/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: Retweet
summary: Remove a retweet
description: Remove a retweet from a tweet and decrement its retweet count.
parameters:
  - in: header
    name: Authorization
    required: true
    schema:
      type: string
      example: "Bearer <JWT>"
    description: JWT token in the format 'Bearer <token>'
  - name: body
    in: body
    description: JSON object containing the user ID and tweet ID
    required: true
    schema:
      type: object
      properties:
        userId:
          type: string
          description: The ID of the user who performed the retweet
        tweetId:
          type: string
          description: The ID of the tweet being unretweeted
responses:
  200:
    description: Successful response
    schema:
      type: object
      properties:
        unRetweet:
          type: integer
          description: The number of retweets removed
  400:
    description: Error response
    schema:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
                description: Description of the error
